sonar.projectKey=banschikovde_fluxview
sonar.organization=banschikovde

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/testdata/**,**/docs/**,**/bin/**

sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=coverage.out
